name: test-local

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test download asset
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download asset action step
      uses: ./ # Uses an action in the root directory
      with:
        version: latest
        repository: JsonRpcNet/JsonRpcNet.Ui
        file: jsonrpcnet-ui.zip
    - name: Unzip output file
      run: unzip jsonrpcnet-ui.zip
